#WAP to compute -9+9-8*6%8-int(19//10/2)|12&14 also explain operator precedence.
s=-9+9-8*6%8-int(19//10/2)|12&14
print(s)
print("the precedance is in order:")
print("Parentheses")
print("Exponent")
print("Multiplication, Division, Floor division, Modulus")
print("Addition, Subtraction")
print("Bitwise shift operators")
print("Bitwise AND")
print("Bitwise XOR")
print("Bitwise OR")
print("Comparisons, Identity, Membership operators")
print("Logical NOT")
print("Logical AND")
print("Logical OR")